# Generated by Django 4.2.3 on 2023-10-14 12:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='заголовок')),
                ('slug', models.CharField(blank=True, max_length=1000, null=True, verbose_name='slug')),
                ('content', models.TextField(verbose_name='содержимое')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='', verbose_name='изображение')),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='дата публикации')),
                ('is_published', models.BooleanField(default=False, verbose_name='опубликовано')),
                ('views_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='кол-во. просмотров')),
            ],
            options={
                'verbose_name': 'статья',
                'verbose_name_plural': 'статьи',
            },
        ),
    ]
